name: thesis-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - numpy
  - pandas
  - pytorch
  - torchvision
  - certifi
  - pip
  - pip:
      - scikit-learn
      - Pillow
      - matplotlib
      - transformers
      - pycocotools
      - iterative-stratification